import Foundation

struct PercentileBands {
    let p5: [Double]
    let p25: [Double]
    let p75: [Double]
    let p95: [Double]

    subscript(index: Int) -> (p5: Double, p25: Double, p75: Double, p95: Double) {
        (p5[index], p25[index], p75[index], p95[index])
    }
}

struct Probability {
    let description: String     // e.g. "Price rises ≥ 10%"
    let value: Double           // 0...1
    var percent: String { String(format: "%.1f%%", value * 100) }
}

struct Forecast {
    let asset: Asset
    let generatedAt: Date
    let horizonDays: Int
    let startPrice: Double
    let medianPath: [Double]
    let bands: PercentileBands
    let probabilities: [Probability]
    let confidence: Double          // 0...1, deliberately conservative
    let volatilityAnnualised: Double
    let disclaimer: String

    static let standardDisclaimer = """
    This forecast is generated by statistical models (Monte Carlo simulation, \
    GARCH volatility estimation, and machine learning). It represents probability \
    ranges, NOT guaranteed predictions. Past patterns do not ensure future results. \
    This is for educational and informational purposes only and does not constitute \
    financial advice. Always consult a qualified financial adviser before making \
    investment decisions.
    """

    var confidenceLabel: String {
        switch confidence {
        case 0..<0.3: "Very Low"
        case 0.3..<0.5: "Low"
        case 0.5..<0.7: "Moderate"
        case 0.7..<0.85: "Moderate-High"
        default: "High"
        }
    }
}
